[relaychain]
default_command = "polkadot"
chain = "dev"

[[relaychain.nodes]]
name = "alice"
validator = true
ws_port = 9944
extra_args = [
  "--force-authoring -lparachain=debug --unsafe-rpc-external --rpc-cors=all",
]

[[relaychain.nodes]]
name = "bob"
validator = true
extra_args = [
  "--force-authoring -lparachain=debug --unsafe-rpc-external --rpc-cors=all",
]

[[parachains]]
id = 1000
add_to_genesis = true
cumulus_based = true
onboard_as_parachain = true

[[parachains.collators]]
args = ["--force-authoring --log=xcm=trace,parachain=trace"]
command = "./target/release/parachain-template-node"
name = "collators-0"
ws_port = 20000

[[parachains.collators]]
args = ["--force-authoring --log=xcm=trace,parachain=trace"]
command = "./target/release/parachain-template-node"
name = "collators-1"
ws_port = 21000
