[package]
name = "my-chain-extensions"
version = "0.1.0"
authors.workspace = true
description = "Parachain chain extensions example"
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
publish = false
